name: test
on: pull_request
jobs:
  test:
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x]
        eslint: [7, 8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Use ESLint ${{ matrix.eslint }}
        run: npm install eslint@${{ matrix.eslint }}
      - run: |
          npm install --silent
          npm run lint
          npm run test
